name: MERN CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install & Build Frontend
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Install & Test Backend
      working-directory: ./server
      run: |
        npm install
        npm test || echo "no tests defined"


